# Generated by Django 3.1.7 on 2023-06-21 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
