# Generated by Django 3.1.7 on 2023-06-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Dob',
            new_name='DOB',
        ),
    ]
