# Generated by Django 3.1.7 on 2023-06-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0004_auto_20230626_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Gener',
            field=models.TextField(blank=True, null=True),
        ),
    ]
