# Generated by Django 3.1.7 on 2023-06-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0005_user_gener'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category_Id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
