# Generated by Django 3.1.7 on 2023-06-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0006_movie_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('seat1', models.IntegerField(blank=True, default=0, null=True)),
                ('seat2', models.IntegerField(blank=True, default=0, null=True)),
                ('seat3', models.IntegerField(blank=True, default=0, null=True)),
                ('seat4', models.IntegerField(blank=True, default=0, null=True)),
                ('seat5', models.IntegerField(blank=True, default=0, null=True)),
                ('seat6', models.IntegerField(blank=True, default=0, null=True)),
                ('seat7', models.IntegerField(blank=True, default=0, null=True)),
                ('seat8', models.IntegerField(blank=True, default=0, null=True)),
                ('seat9', models.IntegerField(blank=True, default=0, null=True)),
                ('seat10', models.IntegerField(blank=True, default=0, null=True)),
                ('seat11', models.IntegerField(blank=True, default=0, null=True)),
                ('seat12', models.IntegerField(blank=True, default=0, null=True)),
                ('seat13', models.IntegerField(blank=True, default=0, null=True)),
                ('seat14', models.IntegerField(blank=True, default=0, null=True)),
                ('seat15', models.IntegerField(blank=True, default=0, null=True)),
                ('seat16', models.IntegerField(blank=True, default=0, null=True)),
                ('seat17', models.IntegerField(blank=True, default=0, null=True)),
                ('seat18', models.IntegerField(blank=True, default=0, null=True)),
                ('seat19', models.IntegerField(blank=True, default=0, null=True)),
                ('seat20', models.IntegerField(blank=True, default=0, null=True)),
                ('seat21', models.IntegerField(blank=True, default=0, null=True)),
                ('seat22', models.IntegerField(blank=True, default=0, null=True)),
                ('seat23', models.IntegerField(blank=True, default=0, null=True)),
                ('seat24', models.IntegerField(blank=True, default=0, null=True)),
                ('seat25', models.IntegerField(blank=True, default=0, null=True)),
                ('seat26', models.IntegerField(blank=True, default=0, null=True)),
                ('seat27', models.IntegerField(blank=True, default=0, null=True)),
                ('seat28', models.IntegerField(blank=True, default=0, null=True)),
                ('seat29', models.IntegerField(blank=True, default=0, null=True)),
                ('seat30', models.IntegerField(blank=True, default=0, null=True)),
                ('seat31', models.IntegerField(blank=True, default=0, null=True)),
                ('seat32', models.IntegerField(blank=True, default=0, null=True)),
                ('seat33', models.IntegerField(blank=True, default=0, null=True)),
                ('seat34', models.IntegerField(blank=True, default=0, null=True)),
                ('seat35', models.IntegerField(blank=True, default=0, null=True)),
                ('seat36', models.IntegerField(blank=True, default=0, null=True)),
                ('seat37', models.IntegerField(blank=True, default=0, null=True)),
                ('seat38', models.IntegerField(blank=True, default=0, null=True)),
                ('seat39', models.IntegerField(blank=True, default=0, null=True)),
                ('seat40', models.IntegerField(blank=True, default=0, null=True)),
                ('seat41', models.IntegerField(blank=True, default=0, null=True)),
                ('seat42', models.IntegerField(blank=True, default=0, null=True)),
                ('seat43', models.IntegerField(blank=True, default=0, null=True)),
                ('seat44', models.IntegerField(blank=True, default=0, null=True)),
                ('seat45', models.IntegerField(blank=True, default=0, null=True)),
                ('seat46', models.IntegerField(blank=True, default=0, null=True)),
                ('seat47', models.IntegerField(blank=True, default=0, null=True)),
                ('seat48', models.IntegerField(blank=True, default=0, null=True)),
                ('seat49', models.IntegerField(blank=True, default=0, null=True)),
                ('seat50', models.IntegerField(blank=True, default=0, null=True)),
                ('days_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.days')),
            ],
        ),
    ]
