# Generated by Django 3.1.7 on 2023-06-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0007_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
