# Generated by Django 3.1.7 on 2023-06-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0008_auto_20230627_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CI',
            field=models.TextField(blank=True, null=True),
        ),
    ]
