# Generated by Django 3.1.7 on 2023-07-03 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0009_user_ci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Gener',
            new_name='Gender',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.TextField(blank=True, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.movie')),
                ('user_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.user')),
            ],
        ),
    ]
