# Generated by Django 3.1.7 on 2023-07-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0010_auto_20230703_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
