from django.db import models
from ..days import Days

class Seats(models.Model):
    Id = models.AutoField(primary_key = True)
    days_Id = models.ForeignKey(Days,on_delete=models.CASCADE)
    seat1 = models.IntegerField(null=True,blank=True,default=0)
    seat2 = models.IntegerField(null=True,blank=True,default=0)
    seat3 = models.IntegerField(null=True,blank=True,default=0)
    seat4 = models.IntegerField(null=True,blank=True,default=0)
    seat5 = models.IntegerField(null=True,blank=True,default=0)
    seat6 = models.IntegerField(null=True,blank=True,default=0)
    seat7 = models.IntegerField(null=True,blank=True,default=0)
    seat8 = models.IntegerField(null=True,blank=True,default=0)
    seat9 = models.IntegerField(null=True,blank=True,default=0)
    seat10 = models.IntegerField(null=True,blank=True,default=0)
    seat11 = models.IntegerField(null=True,blank=True,default=0)
    seat12 = models.IntegerField(null=True,blank=True,default=0)
    seat13 = models.IntegerField(null=True,blank=True,default=0)
    seat14 = models.IntegerField(null=True,blank=True,default=0)
    seat15 = models.IntegerField(null=True,blank=True,default=0)
    seat16 = models.IntegerField(null=True,blank=True,default=0)
    seat17 = models.IntegerField(null=True,blank=True,default=0)
    seat18 = models.IntegerField(null=True,blank=True,default=0)
    seat19 = models.IntegerField(null=True,blank=True,default=0)
    seat20 = models.IntegerField(null=True,blank=True,default=0)
    seat21 = models.IntegerField(null=True,blank=True,default=0)
    seat22 = models.IntegerField(null=True,blank=True,default=0)
    seat23 = models.IntegerField(null=True,blank=True,default=0)
    seat24 = models.IntegerField(null=True,blank=True,default=0)
    seat25 = models.IntegerField(null=True,blank=True,default=0)
    seat26 = models.IntegerField(null=True,blank=True,default=0)
    seat27 = models.IntegerField(null=True,blank=True,default=0)
    seat28 = models.IntegerField(null=True,blank=True,default=0)
    seat29 = models.IntegerField(null=True,blank=True,default=0)
    seat30 = models.IntegerField(null=True,blank=True,default=0)
    seat31 = models.IntegerField(null=True,blank=True,default=0)
    seat32 = models.IntegerField(null=True,blank=True,default=0)
    seat33 = models.IntegerField(null=True,blank=True,default=0)
    seat34 = models.IntegerField(null=True,blank=True,default=0)
    seat35 = models.IntegerField(null=True,blank=True,default=0)
    seat36 = models.IntegerField(null=True,blank=True,default=0)
    seat37 = models.IntegerField(null=True,blank=True,default=0)
    seat38 = models.IntegerField(null=True,blank=True,default=0)
    seat39 = models.IntegerField(null=True,blank=True,default=0)
    seat40 = models.IntegerField(null=True,blank=True,default=0)
    seat41 = models.IntegerField(null=True,blank=True,default=0)
    seat42 = models.IntegerField(null=True,blank=True,default=0)
    seat43 = models.IntegerField(null=True,blank=True,default=0)
    seat44 = models.IntegerField(null=True,blank=True,default=0)
    seat45 = models.IntegerField(null=True,blank=True,default=0)
    seat46 = models.IntegerField(null=True,blank=True,default=0)
    seat47 = models.IntegerField(null=True,blank=True,default=0)
    seat48 = models.IntegerField(null=True,blank=True,default=0)
    seat49 = models.IntegerField(null=True,blank=True,default=0)
    seat50 = models.IntegerField(null=True,blank=True,default=0)


